// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/practice.tsx";
import * as $3 from "./routes/set-name.tsx";
import * as $$0 from "./islands/game.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/practice.tsx": $2,
    "./routes/set-name.tsx": $3,
  },
  islands: {
    "./islands/game.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
