// Packs dist/ into one Cloudflare Worker module (.worker/index.js) that serves the static SPA:
// immutable caching for hashed assets, SPA fallback to index.html, no KV/R2/asset-upload needed.
// (Plain Worker uploads work everywhere, including behind credential-injecting proxies.)
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, join, relative } from "node:path";

const root = new URL("../dist/", import.meta.url).pathname;
const TYPES = {
  ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8",
  ".csv": "text/csv; charset=utf-8", ".json": "application/json", ".webmanifest": "application/manifest+json",
  ".png": "image/png", ".webp": "image/webp", ".ico": "image/x-icon", ".svg": "image/svg+xml", ".txt": "text/plain; charset=utf-8",
};
const TEXT = new Set([".html", ".js", ".css", ".csv", ".json", ".webmanifest", ".svg", ".txt"]);

const files = {};
(function walk(dir) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    const ext = extname(f);
    const buf = readFileSync(p);
    files["/" + relative(root, p)] = { type: TYPES[ext] ?? "application/octet-stream", bin: !TEXT.has(ext), body: TEXT.has(ext) ? buf.toString("utf8") : buf.toString("base64") };
  }
})(root);
delete files["/_headers"]; delete files["/_redirects"];

const src = `// generated by tools/build-worker.mjs — do not edit
const FILES = ${JSON.stringify(files)};
const decode = (b64) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
const cache = new Map();
function body(path) {
  const f = FILES[path];
  if (!f.bin) return f.body;
  return cache.get(path) ?? (cache.set(path, decode(f.body)), cache.get(path));
}
export default {
  fetch(request) {
    if (request.method !== "GET" && request.method !== "HEAD") return new Response("Method Not Allowed", { status: 405 });
    let path = new URL(request.url).pathname;
    let file = FILES[path];
    // unknown paths with no extension are client-side routes -> the app shell
    if (!file && !/\\.[a-z0-9]+$/i.test(path)) { path = "/index.html"; file = FILES[path]; }
    if (!file) return new Response("Not found", { status: 404 });
    const headers = {
      "content-type": file.type,
      "cache-control": path.startsWith("/assets/") ? "public, max-age=31536000, immutable" : "no-cache",
      "x-content-type-options": "nosniff",
    };
    return new Response(request.method === "HEAD" ? null : body(path), { headers });
  },
};
`;
mkdirSync(new URL("../.worker/", import.meta.url), { recursive: true });
writeFileSync(new URL("../.worker/index.js", import.meta.url), src);
console.log(`worker: ${Object.keys(files).length} files, ${(src.length / 1024).toFixed(0)}KB source`);
