-- Reidle schema. All app access goes through the RPCs in the next migration;
-- tables are closed to clients except `battles` (realtime + direct state writes).

create table players (
  name text primary key,
  user_id uuid unique references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create table words (word text primary key);
create table answers (answer text primary key);

create table daily_words (
  day date primary key,
  word text not null references words (word),
  answer text not null references answers (answer)
);

create table challenges (
  challenge_id integer generated always as identity primary key,
  starting_word text not null references words (word),
  answer text not null references answers (answer),
  created_at timestamptz not null default now()
);
create index challenges_created_at_idx on challenges (created_at);

create table submissions (
  submission_id bigint generated always as identity primary key,
  day date not null default current_date,
  name text not null references players (name),
  paste text not null default '',
  playback jsonb not null default '{"events":[]}',
  challenge_id integer references challenges (challenge_id),
  "time" double precision not null check ("time" > 0),
  penalty double precision not null default 0 check (penalty >= 0),
  word text not null,
  "rank" integer not null default 1,
  created_at timestamptz not null default now()
);
create unique index submissions_daily_once on submissions (day, name)
  where challenge_id is null;
create unique index submissions_challenge_once on submissions (challenge_id, name)
  where challenge_id is not null;
create index submissions_day_idx on submissions (day);
create index submissions_name_idx on submissions (name);
create index submissions_challenge_idx on submissions (challenge_id);

create table checkpoints (
  name text primary key references players (name),
  day date not null default current_date,
  penalty double precision not null default 0,
  history jsonb not null default '[]',
  created_at timestamptz not null default now()
);

create table messages (
  message_id integer generated always as identity primary key,
  name text not null references players (name),
  message text not null check (length(message) between 1 and 4000),
  likes text[] not null default '{}',
  created_at timestamptz not null default now()
);
create index messages_created_at_idx on messages (created_at desc);

create table message_reads (
  name text primary key references players (name),
  last_read timestamptz not null
);

create table winners (
  week date primary key,
  name text not null
);

create table battles (
  battle_id integer generated by default as identity primary key,
  state jsonb not null default '{}',
  users jsonb not null default '[]',
  updated_at timestamptz not null default now()
);
-- battle 7 is the always-on party room
insert into battles (battle_id) values (7);
select setval(pg_get_serial_sequence('battles', 'battle_id'), 100);

-- Lock every table; RPCs (security definer) are the only door.
alter table players enable row level security;
alter table words enable row level security;
alter table answers enable row level security;
alter table daily_words enable row level security;
alter table challenges enable row level security;
alter table submissions enable row level security;
alter table checkpoints enable row level security;
alter table messages enable row level security;
alter table message_reads enable row level security;
alter table winners enable row level security;
alter table battles enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- Battles: live rooms are written by the clients (broadcast + state sync).
grant select, update on battles to authenticated;
create policy battles_read on battles for select to authenticated using (true);
create policy battles_write on battles for update to authenticated
  using (true) with check (true);
alter publication supabase_realtime add table battles;
alter table battles replica identity full;

-- Name-only auth: the auth trigger links (or creates) the player row.
create function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into players (name, user_id)
  values (new.raw_user_meta_data ->> 'name', new.id)
  on conflict (name) do update set user_id = excluded.user_id
    where players.user_id is null;
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function handle_new_user();
